services:
  jobmanager:
    image: custom-pyflink
    build: .
    pull_policy: never
    container_name: "jobmanager"
    hostname: "jobmanager"
    platform: "linux/amd64"
    env_file:
      - flink-env.env
    expose:
      - "6123"
    ports:
      - "8081:8081"
    volumes:
      # - ./:/opt/flink/usrlib  # Commented out to avoid mounting the entire context
      - ./src/:/opt/src
    command: jobmanager
    extra_hosts:
      - "host.docker.internal:host-gateway" #// Access services on the host machine from within the Docker container
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    networks:
      - livestream-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  # Flink task manager
  taskmanager:
    image: custom-pyflink
    pull_policy: never
    container_name: "taskmanager"
    platform: "linux/amd64"
    env_file:
      - flink-env.env
    expose:
      - "6121"
      - "6122"
    volumes:
      # - ./:/opt/flink/usrlib  # Commented out to avoid mounting the entire context
      - ./src/:/opt/src
    depends_on:
      - jobmanager
    command: taskmanager --taskmanager.registration.timeout 5 min
    extra_hosts:
      - "host.docker.internal:host-gateway" #// Access services on the host machine from within the Docker container
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 30
        parallelism.default: 3
    networks:
      - livestream-net
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "6122"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  #hot-reload:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  container_name: hot_reload
  #  depends_on:
  #    - jobmanager
  #  volumes:
  #    - ./src:/opt/src
  #  networks:
  #    - livestream-net
  #  environment:
  #    - JOBMANAGER_URL=http://jobmanager:8081

networks:
  livestream-net:
    external: true